### PR TITLE
to_h will only call methods with zero args

### LINKED ISSUE #4: #to_h serializes all instance methods
Hi,

I'd like to be able to use standard Ruby methods in my `ImmutableStruct`. I'm currently having problems with this one:

```ruby
it "should allow #== method to be overriden" do
  klass = ImmutableStruct.new(:id, :flappy) do
    def ==(other)
      self.id == other.id
    end
  end
  instance = klass.new(id: 1, flappy: 'bird')
  instance.to_h.should == {id: 1, flappy: 'bird'}
end
```

Just because `#to_h` [processes all instance methods](https://github.com/stitchfix/immutable-struct/blob/df5b280520abcac144e46dde4287264a50df7316/lib/immutable-struct.rb#L72), regardless of their intent and it fails when calling methods with arity > 0:

```
1) ImmutableStruct to_h should allow #== method to be overriden
     Failure/Error: def ==(other)
     ArgumentError:
       wrong number of arguments (0 for 1)
     # ./spec/immutable_struct_spec.rb:128:in `=='
     # ./lib/immutable-struct.rb:72:in `block (3 levels) in new'
     # ./lib/immutable-struct.rb:72:in `each'
     # ./lib/immutable-struct.rb:72:in `inject'
     # ./lib/immutable-struct.rb:72:in `block (2 levels) in new'
     # ./spec/immutable_struct_spec.rb:133:in `block (3 levels) in <top (required)>'
```

Moreover, if the user decides to implement `#to_s`, domain-related logic or even a conversion method, these would be serialized as well with unexpected consequences depending on their arity.

IMO this issue raises an interesting question: is it really necessary to serialize all instance methods? In Ruby's [`Struct#to_hash`](http://ruby-doc.org/core-2.2.0/Struct.html#method-i-to_h) only the struct members (ie. those defined in the constructor) are serialized. So I'd expect `ImmutableStruct` to behave in the same way.

If this is OK with you I'd be happy to submit a PR.

Kind regards,
//nando

### PR DESCRIPTION
**Pull request by davetron5000**
This fixes #4 insomuch as it won't call methods that aren't zero-args.

This still doesn't address all the issues that @nandosola brought up in #5.

### CODE REVIEW

File: spec/immutable_struct_spec.rb [hunk 1]
```diff
@@ -103,14 +104,61 @@ def self.from_array(array)
...
+          minor: "ayup",
+          minor?: true,
+          location: nil,
+          aliases: [ "Rudyard", "Roozoola"],
+          nick_name: "bob",
+        }
+      end
+    end
+    context "additional method that takes arguments" do
+      it "should not call the additional method" do
```
Comment (davetron5000) [inline spec/immutable_struct_spec.rb]: This revealed the core of the issue

File: spec/immutable_struct_spec.rb [hunk 2]
```diff
@@ -103,14 +104,61 @@ def self.from_array(array)
...
+        klass = ImmutableStruct.new(:name, :minor?, :location, [:aliases]) do
+          def nick_name
+            'bob'
+          end
+          def to_json
+            to_h.to_json
+          end
+        end
+        instance = klass.new(name: "Rudy", minor: "ayup", aliases: [ "Rudyard", "Roozoola" ])
+        expect {
```
Comment (davetron5000) [inline spec/immutable_struct_spec.rb]: I don't know if this is fixable without either some way to "flag" methods as "don't include in serialization" or some version of #5.

I feel like the use-case you want generally is "serialize everything but this method:" but I'm not 100% sure.

**Comment by davetron5000** [comment]
ok, it's doing a weird pointless second build.
